contracts/test/data/MultiSigTCD.test.js
Test about active provider is in TCD.test.js already. Remove test in this file for easier maintenance.
=> Remove unneccesary test

band-solidity/README.md, band-solidity/contracts/data/BandLib.sol, band-solidity/package.json
Simplify how to connect with QueryInterface of band protocol feed.
=> Band solidity

app/src/actions/transaction.js, app/src/components/ConvertRevenueModal/ConvertRevenueModal.js, app/src/components/ConvertRevenueModal/index.js, app/src/components/ModalEntry/ModalEntryRender.js, app/src/components/PendingTransaction.js, app/src/pages/CommunityDataProvider/ProviderListBody.js, app/src/pages/CommunityDataProvider/ProviderListBodyRender.js, app/src/pages/CommunityDataProvider/ProviderListRender.js, app/src/sagas/tcd.js, app/src/sagas/transaction.js
Fixes #26 
- Add max withdraw button
- Add revenue column
- Add ConvertRevenue modal
- Add Convert revenue to stake button
- Add withdraw revenue button
- Add  stake revenue type badge in transaction popup
=> Add revenue functionality

docs/devs/connect-with-band.md, docs/devs/data-query.md
Edit documents follow library and truffle-box
=> Edit developer documents

band-solidity/contracts/data/BandLib.sol, band-solidity/package.json
- Update new address of new tcd dataset.
- Change how to query spot price of price data feed
=> Update band-solidity lib for 1  tcd

docs/datasets/financial-kovan.md, docs/datasets/lottery-kovan.md, docs/datasets/sport-kovan.md, docs/datasets/web-oracle.md, docs/devs/data-query.md
- Update address in every dataset
- Add how to request data
=> Update address dataset

web/src/pages/Developer.js
add a link to developer doc on the developer page
=> add link, change dataset oracle address

app/src/actions/transaction.js, app/src/components/BuySellModal/BuySellModal.js, app/src/components/ConvertRevenueModal/ConvertRevenueModal.js, app/src/components/DepositWithdrawModal/DepositWithdrawModal.js, app/src/components/PendingTransaction.js, app/src/pages/CommunityDataProvider/CommunityDataProvider.js, app/src/pages/CommunityDataProvider/ProviderList.js, app/src/pages/CommunityDataProvider/ProviderListBody.js, app/src/pages/CommunityDataProvider/ProviderListBodyRender.js, app/src/sagas/transaction.js, app/src/selectors/balances.js, app/src/utils/bignumber.js
Fixes #55 
- Add action type in wallet (Buy, Sell, Vote, Propose, Withdraw, Deposit)
=> Add type in wallet tx

app/src/components/DepositWithdrawModal/DepositWithdrawModal.js, app/src/pages/CommunityDataProvider/ProviderListBody.js, app/src/pages/CommunityDataProvider/ProviderListBodyRender.js, app/src/selectors/balances.js, app/src/utils/bignumber.js
Fixes #50 
- add max withdraw and deposit button
=> Add max withdraw deposit button

go/adapter/currencyconverter.go, go/adapter/currencyconverter_test.go, go/adapter/ratesapi.go, go/adapter/ratesapi_test.go, go/go.mod, go/go.sum
- Add ratesapi and currencyconverterapi source and test
=> Update 2 forex market

go/adapter/alphavantageforex.go, go/adapter/alphavantageforex_test.go, go/adapter/currencyconverter.go
- Update currencyconverter to get gold and silver price
- Add alphavantage forex source
=> Update alphaforex and gold price

go/adapter/alphavantagestock.go, go/adapter/alphavantagestock_test.go
- Add alpha-vantage to get stock price
=> Add alpha vantage stock source

go/adapter/financialmodelprep.go, go/adapter/financialmodelprep_test.go
Add financial model prep provider
=> Update financial model prep source

go/adapter/freeforexapi.go, go/adapter/freeforexapi_test.go
Add `https://www.freeforexapi.com` endpoint source
=> Implemented freeforexapi source

app/src/pages/CommunityDataProvider/ProviderListBody.js, app/src/pages/CommunityDataProvider/ProviderListBodyRender.js
Fixes #51
- disabled deposit button when remaining token = 0
=> disabled deposit button when remaining token = 0

app/src/components/PriceGraph/PriceGraphRender.js, app/src/components/TCDSelector/TCDSelectorRender.js, app/src/utils/tcds.js
Fix missing things for 1 TCD kovan test net
=> Fix deploy koven test

go/adapter/alphavantageforex.go, go/adapter/alphavantagestock.go, go/adapter/bancor.go, go/adapter/bitfinex.go, go/adapter/bitstamp.go, go/adapter/bittrex.go, go/adapter/coinbase.go, go/adapter/coinmarketcap.go, go/adapter/cryptocompare.go, go/adapter/currencyconverter.go, go/adapter/financialmodelprep.go, go/adapter/gemini.go, go/adapter/kraken.go, go/adapter/kyber.go, go/adapter/openmarketcap.go, go/adapter/ratesapi.go, go/adapter/uniswap.go, go/adapter/worldtradingdata.go
=> Change HexToHash(0) to Hash{}

go/node/main.go
- 2 endpoint ready to get signature
=> Update node provider send data and aggregate

web/src/components/Navbar.js
Fix #118 
remove airdrop nav link both mobile and desktop
=> remove airdrop nav link

app/src/components/Navbar/NavbarRender.js
=> fix alignment, change indicatorSeparator

app/src/actions/community.js, app/src/components/CommunityDescription/CommunityDescription.js, app/src/components/CommunityDescription/CommunityDescriptionRender.js, app/src/reducers/community.js, app/src/sagas/index.js
=> add tcd, parameter address

web/src/pages/Developer.js
Fixes #114 
- Add Blinking animation on BandProtocol.com
=> Blinking developer page

go/eth/provider.go, go/eth/provider_test.go, go/eth/rpc.go, go/eth/util.go, go/eth/util_test.go, go/node/main.go
- Add 3 functions to get active providers, check if address is a provider and verify dataset address.
- Test on each function in success and failed test.
- Rename environment variable.
=> Implement provider functions

docs/.vuepress/theme/components/SidebarLink.vue, docs/.vuepress/theme/styles/config.styl
=> change link color to #1242ea

go/adapter/aggmedian.go, go/adapter/aggmedian_test.go, go/adapter/alphavantageforex.go, go/adapter/alphavantagestock.go, go/adapter/bancor.go, go/adapter/bitfinex.go, go/adapter/bitstamp.go, go/adapter/bittrex.go, go/adapter/coinmarketcap.go, go/adapter/coinmarketcap_test.go, go/adapter/cryptocompare.go, go/adapter/currencyconverter.go, go/adapter/financialmodelprep.go, go/adapter/freeforexapi.go, go/adapter/kraken.go, go/adapter/kyber.go, go/adapter/onchainfx.go, go/adapter/openmarketcap.go, go/adapter/ratesapi.go, go/adapter/types.go, go/adapter/uniswap.go, go/adapter/worldtradingdata.go, go/node.yaml, go/node/main.go
- Add `Configure` function to each adapters
- Node can config and run by
```
go run node/main.go node
```
'node' is your config file
- Update aggMedian test
=> Update adapter add Configure function

app/src/components/DatasetTab.js, app/src/data/detail/price.js, app/src/data/fetcher/LotteryFetcher.js, app/src/data/fetcher/PriceFetcher.js, app/src/data/fetcher/SportFetcher.js, app/src/pages/CommunityDataSet/CommunityDataSetLottery.js, app/src/pages/CommunityDataSet/CommunityDataSetPrice.js, app/src/pages/CommunityDataSet/CommunityDataSetSport.js
- Add filter button to
Fixes #145
=> App add filter button

go/eth/rpc.go, go/eth/rpc_test.go
replace "eth_signTransaction" with "eth_sendTransaction"
=> fix sending tx to work with geth 1.9.2

go/coord.yaml, go/coordinator/main.go, go/eth/rpc.go, go/go.sum, go/node/main.go, go/reqmsg/msg.go, go/reqmsg/util.go, go/reqmsg/util_test.go
- Now coordinator can get data from each node to collect signature and report to chain
- Can send or get transaction data to send later
=> Coordinator node and provider

web/package.json
=> disable generate sourcemap

go/adapter/coinmarketcap.go, go/adapter/coinmarketcap_test.go
- Add cache layer that request data if data is older than 5 minutes
- Change apikey from `X-CMC_PRO_API_KEY` to `CoinMarketCapApikey`
=> Add cache for CoinMarketCap source

app/src/data/detail/price.js, app/src/data/fetcher/PriceFetcher.js, app/src/ui/colors.js
=> Fix prices fx

go/coordinator/main.go
- Make other request by ascii key
=> Transfrom non hex string to hex-string

web/src/pages/Company/Career.js
=> fix typo in band web

go/eth/rpc.go, go/node/main.go
- Remove rpc endpoint from provider node.
- Make everything worked
=> Update node don't need rpc endpoint

contracts/contracts/token/SnapshotToken.sol, contracts/package.json, contracts/test/BandMockExchange.test.js, contracts/test/BandToken.test.js, contracts/test/CommunityToken.test.js, contracts/test/Equation.test.js, contracts/test/LockableToken.test.js, contracts/test/Parameters.test.js, contracts/test/VestingWallet.test.js, contracts/test/bonding-curve/BondingCurve.test.js, contracts/test/bonding-curve/ParameterizedBondingCurve.test.js, contracts/test/data/MultiSigTCD.test.js, contracts/test/data/QueryTCR.test.js, contracts/test/data/TCD.test.js, contracts/test/data/WhiteList.test.js, contracts/test/utils/Aggregator.test.js, contracts/yarn.lock
=> Change test contract

web/package.json, web/src/components/Footer.js, web/src/components/Navbar.js, web/src/pages/Developer.js, web/yarn.lock
Let's remove forum links for now and re-add it as we launch hackathon
=> Temporarily remove forum links

truffle-box/contracts/GroceryStore.sol, truffle-box/package.json, truffle-box/yarn.lock
- Update dependency in example project
- Change how to query price
- Deploy on remix worked
=> Update truffle example project to new key version

contracts/contracts/utils/EndpointDatabase.sol, contracts/contracts/utils/ProviderEndpoint.sol
Add provider endpoint contract store endpoint for data providers
=> Add provider endpoint contract

go/coord.yaml, go/coordinator/main.go
- Remove provider endpoint in config, ask from blockchain instead.
- Deploy 2 contracts for testing and deployment.
=> Provider endpoint call

band-solidity/package.json, truffle-box/contracts/GasStation.sol, truffle-box/contracts/GroceryStore.sol, truffle-box/package.json, truffle-box/yarn.lock
- Release on npm
- Update truffle-box code
=> Dump band-solidity to 0.0.7

app/src/actions/current.js, app/src/components/LoginModal/LoginModal.js, app/src/components/LoginModal/LoginModalRender.js, app/src/components/Navbar/Navbar.js, app/src/components/Navbar/NavbarRender.js, app/src/reducers/current.js, app/src/sagas/current.js, app/src/sagas/index.js, app/src/selectors/current.js
- Add LoginModal
- Add Metamask (user, provider)
=> Support Ethereum and Band Wallet

app/public/index.html
=> add google analysis

app/src/components/OrderHistory/OrderHistory.js, app/src/components/Richlist/Richlist.js, app/src/components/TransferHistory/TransferHistory.js, app/src/pages/CommunityDataProvider/ProviderList.js, app/src/pages/CommunityProposal/CommunityProposal.js, app/src/ui/theme.js
- Provider lists
- Order History list
- Transfer list
- Rich list
- Proposal list
- change hover btn color
=> Increase Interval time on lists

app/src/sagas/transaction.js
- change error message from wallet
=> change error wallet message

web/src/components/Footer.js
- Change image at Join community
=> fix join community footer web

go/driver/binance.go, go/driver/binance_test.go, go/go.sum
=> add BTC-USDT

go/driver/types.go, go/node_price.yaml
Update binance driver to node provider
=> Add binance driver to node provider

go/driver/binance.go, go/driver/binance_test.go
- Use bid and ask order price instead last trade
=> Update binance driver

app/src/index.js, app/src/pages/MobilePage.js, app/src/utils/detectmobilebrowser.js
Fixes #235 
- Let's the current version of BandApp show "not support" message when opening from a mobile device.
=> add does not support mobile

band-solidity/contracts/Band.sol, band-solidity/package.json, truffle-box/package.json, truffle-box/yarn.lock
- Other contract doesn't need to`abi.encodepacked` string before send to Oracle interface
=> Change band-soldity key type from bytes to string

app/src/data/detail/price.js
=> Add BTC-USDT to crypto page

go/coordinator/main.go, go/dt/answer.go, go/eth/rpc.go, go/go.mod
- Dump request log to file (ex. 2019-09-17.log)
- Each request will look like this
```
2595011731,1568718488238,Request,0xa24dF0420dE1f3b8d740A52AAEB9d55d6D64478e,0x53504f5450582f4254432d555344,[::1]:56059,false
2595011731,1568718489252,Report,0xDa7AFDeE902A41769479349373EF24D19368a9f1,Answered,0x000000000000000000000000000000000000000000000227c0efa815bd300000,1568718488,27,0x4e7d4eeb554c6859a0be19a81ae730664918bacc509f2c656ae88c3805f5c997,0x5eb685b79c53e90c5d2d7958ccb68d1f47faecaeaf2080510b212f178a009636
2595011731,1568718489314,Report,0xDA7afa8f087AA2571276b17dBe45A4097C380eff,Answered,0x000000000000000000000000000000000000000000000227c0efa815bd300000,1568718489,28,0x1046502196ad190f094d08e2bdd1180e9f548d0fd37524c6c5f45cbc50a8b99c,0x27f5af8ca6de16d74385ced296f2bd86358e51cf1d47c9358600fed …
```
=> Update coordinator log

app/src/components/Navbar/NavbarRender.js, app/src/components/table/PriceTable.js, app/yarn.lock
upgrade dependencies in yarn.lock
fix error image size due to new rebass version
=> Upgrade and fix package

app/src/sagas/index.js, app/src/utils/network.js
=> add ropsten network

app/src/components/DepositWithdrawModal/DepositWithdrawModal.js, app/src/pages/CommunityDataProvider/ProviderListBodyRender.js, app/src/pages/CommunityDataProvider/ProviderListRender.js, app/src/utils/bignumber.js
remove contract address
add more digits in your stake and revenue stake
=> Update provider list

app/src/pages/CreateCommunity/CreateCommunity.js, app/src/utils/helper.js
Make inflation ratio show understandable data (from 0.0000..% per second to 5.0000 % per year)
=> Add new type of parameter

app/src/sagas/index.js
=> change wallet endpoint

app/src/utils/tcds.js
change docs from Kovan to Mainnet
=> change XFN doc to mainnet

graph/band/mappings/BandToken.ts, graph/band/mappings/BondingCurve.ts, graph/band/mappings/DatasetToken.ts, graph/band/mappings/OffchainAggTCD.ts, graph/band/mappings/Parameters.ts, graph/band/mappings/TxSubscriber.ts, graph/band/schema.graphql
**Test it on**
[SUBGRAPH](https://thegraph.com/explorer/subgraph/evilpeach/band-tx-subscriber?query=Example%20query)
Network : Ropsten
dApp: [Staking Portal](http://band-sp-master.surge.sh/)
=> add tx subscriber on the graph 

graph/band/mappings/Parameters.ts
See https://thegraph.com/explorer/subgraph/sorawit/band-mainnet
=> Update thegraph to run without errors

contracts/contracts/exchange/BondingCurve.sol, contracts/test/bonding-curve/BondingCurve.test.js
Fixes implement `buy2` and `sell2` function with test cases
=> add inv and test

contracts/contracts/exchange/BondingCurve.sol, contracts/contracts/utils/Expression.sol, contracts/migrations/2_deploy_helper_factory.js, contracts/migrations/3_deploy_band_factory.js, contracts/migrations/4_deploy_tcr_community.js, contracts/migrations/5_deploy_price_community.js, contracts/migrations/6_deploy_lottery_community.js, contracts/migrations/7_deploy_sport_community.js, contracts/migrations/8_deploy_web_crawler_community.js, contracts/test/Parameters.test.js, contracts/test/bonding-curve/BondingCurve.test.js, contracts/test/bonding-curve/ParameterizedBondingCurve.test.js, contracts/test/data/MajorityAggTCD.test.js, contracts/test/data/MedianAggTCD.test.js, contracts/test/data/MultiSigTCD.test.js, contracts/test/data/OffchainAggTCD.test.js, contracts/test/data/QueryTCR.test.js, contracts/test/data/TCD.test.js, contracts/test/data/WhiteList.test.js
- Update expression interface
- Show how to use inverse in bonding curve contract
=> Expression evaluation inverse interface

graph/band/mappings/OffchainAggTCD.ts
- Fix ownership bug by calculate voter owner ship by current state and event instead ask blockchain
=> Change from ask chain to accumulate from current state
